# Generated by Django 6.0.2 on 2026-02-26 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.PositiveIntegerField()),
                ('vida', models.PositiveIntegerField()),
                ('vida_max', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Arquero',
            fields=[
                ('personaje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.personaje')),
                ('precision', models.PositiveIntegerField(default=0)),
            ],
            bases=('app.personaje',),
        ),
        migrations.CreateModel(
            name='Guerrero',
            fields=[
                ('personaje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.personaje')),
                ('armadura', models.PositiveIntegerField(default=0)),
            ],
            bases=('app.personaje',),
        ),
        migrations.CreateModel(
            name='Mago',
            fields=[
                ('personaje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.personaje')),
                ('mana', models.PositiveIntegerField(default=0)),
            ],
            bases=('app.personaje',),
        ),
    ]
