# Generated by Django 6.0.2 on 2026-03-03 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsEntrenar',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('nivel', models.PositiveIntegerField()),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='app.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='StatsLuchar',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('p1_win', models.BooleanField()),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='app.personaje')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='app.personaje')),
            ],
        ),
    ]
