# Generated by Django 6.0.2 on 2026-03-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='usuario',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
