# Generated by Django 6.0.2 on 2026-03-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_personaje_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dni',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
