# Generated by Django 6.0.2 on 2026-03-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perfil_dni_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fnac',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
